
infrastructures:
  - repo_path: "/home/atropos/projects/Infra/k3s" 
    infra_path: "/home/atropos/projects/Infra/k3s/apps"
    repo_url: "git@gitlab.atro.xyz:inf/charts.git"
  - repo_path: "/home/atropos/projects/Infra/k3s"
    infra_path: "/home/atropos/projects/Infra/k3s/core"
    repo_url: "git@github.com:atropos112/k3s.git"
  - repo_path: "/home/atropos/projects/Infra/pipelines"
    repo_url: "git@gitlab.atro.xyz:inf/pipelines.git"


overrides:
  metallb:
    spec:
      ignoreDifferences:
        - group: apiextensions.k8s.io
          jsonPointers:
            - /spec/conversion
          kind: CustomResourceDefinition
  datree:
    spec:
      ignoreDifferences:
        - group: ""
          jsonPointers:
            - /data
          kind: Secret
  cilium:
    spec:
      ignoreDifferences:
        - group: ""
          jsonPointers:
            - /data
          kind: Secret
  argocd:
    spec:
      ignoreDifferences:
        - group: ""
          jsonPointers:
            - /data/admin.passwordMtime
          kind: Secret
  tempo:
    spec:
      ignoreDifferences:
        - group: ""
          jsonPointers:
            - /data
          kind: Secret
        - group: apps
          jsonPointers:
            - /spec/template/metadata/annotations
          kind: Deployment
  harbor: 
    spec:
      ignoreDifferences:
        - group: ""
          jsonPointers:
            - /data
          kind: Secret
        - group: apps
          jsonPointers:
            - /spec/template/metadata/annotations
          kind: Deployment